"""initial schema — autogenerated via metadata.create_all on first run."""
from alembic import op

revision = "0001_init"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # Tables are created via Base.metadata.create_all() at app startup for dev.
    # For production, run `alembic revision --autogenerate -m "init"` to capture full DDL.
    pass

def downgrade(): pass
